title:TaneRS > Road to Data Science
description: >- # this means to ignore newlines until "baseurl:"
  To Record & Share
baseurl: "/blog" 
url: "http://tan35esha.github.io" 
github_username:  tan35esha
theme: jekyll-theme-hacker
