title: TaneRS DS M/DL AI
description: >- 
  This site is used to record and share my DS, ML, DL, and AI learning.

baseurl: "/road-to-data-science"
theme: jekyll-theme-midnight

# Search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [index.md, search.html]