title: TaneRS doning DS, ML, DL, and AI
description: >- 
This site is used to record and share my DS, ML, DL, and AI learning.

baseurl: "/"
theme: jekyll-theme-midnight

# Search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [index.md, search.html]